### PR TITLE
release-schema: add lots to schema and lots example to README.md

### PR DESCRIPTION
**Pull request by odscjen**
This is hopefully a simple one to review, added `Lot` to the release-schema, added a new example, updated the Legal Context to link to the 3 eForms BT's that need this and added the lot dependency to the extension.json

### CODE REVIEW

**Comment by duncandewhurst** [comment]
@jpmckinney before reviewing this PR in detail, I want to double-check that you're happy with the mapping of BT-14 (Documents Restricted), BT-615 (Documents Restricted URL) and BT-707 (Documents Restricted Justification) to this extension. The mapping was proposed by Colin and is presumably based on the mapping of F02 I.3 in the EU profile. However, it's not clear to me that a restriction on access to certain procurement documents necessarily means that there is a fee for access.

**Comment by jpmckinney** [comment]
Ah, yes, quite right. I had created this issue, which we now need to resolve: https://github.com/open-contracting/ocds-extensions/issues/178

**Comment by duncandewhurst** [comment]
@odscjen based on the outcome of https://github.com/open-contracting/ocds-extensions/issues/178, I think this PR is no longer needed. However, we will need to update `guidance.yaml` and the document details extension, per that issue. Are you happy to do that?

**Comment by odscjen** [comment]
@duncandewhurst sounds good, I'll close this PR and update the guidance as per https://github.com/open-contracting/ocds-extensions/issues/178

**Pull request closed without merging**
